# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:57
from __future__ import unicode_literals

from django.db import migrations
import uuid # added

# add function: 
def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('catalog', 'Author') # 'myapp' -> 'catalog', 'MyModel' -> 'Author'
    for row in MyModel.objects.all():
        row.slug = uuid.uuid4() # 'row.uuid' -> 'row.slug'
        row.save(update_fields=['slug']) # ['uuid'] -> ['slug']

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_author_slug'),
    ]

    operations = [
    	migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop), # added (remove reversibility?)
    ]
