# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models # added models
import uuid # added uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170922_1957'),
    ]

    operations = [
    	migrations.AlterField( # changed from AddField
            model_name='book',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
